#!/usr/bin/env python
import argparse
import os
import sys

import imas

from gui.gui_methods import create_workflow_param_from_file
from hcdworkflow.hcd_workflow import HCDWorkflow
from hcdworkflow.workflow_dbhelper import WorkflowDbHelper, get_ids

isWaveformCookerPresent = True
try:
    from waveform_cooker import add_dynamic
except:
    isWaveformCookerPresent = False



# Management of input arguments
parser = argparse.ArgumentParser(
    description="---- Run the H&CD workflow without the interface"
)
parser.add_argument(
    "-c", "--config_folder", help="input configuration folder", required=True
)

args = vars(parser.parse_args())
config_folder = args["config_folder"]

config_folder_path = os.path.abspath(config_folder)

rootPath = os.path.dirname(os.path.abspath(__file__))
inputworkflow_xml = os.path.join(config_folder_path, "input_workflow.xml")

wf_parameters = create_workflow_param_from_file(inputworkflow_xml)[
    "workflow_parameters"
][0]

input_user_or_path = wf_parameters["input_user_or_path"][0]
input_database = wf_parameters["input_database"][0]
input_backend="MDSPLUS"
if "input_backend" in wf_parameters:
    input_backend = wf_parameters["input_backend"][0]
output_user_or_path = wf_parameters["output_user_or_path"][0]
output_database = wf_parameters["output_database"][0]

output_backend="MDSPLUS"
if "output_backend" in wf_parameters:
    output_backend = wf_parameters["output_backend"][0]
shot_nr = wf_parameters["shot_nr"][0]
run_in = wf_parameters["run_in"][0]
run_out = wf_parameters["run_out"][0]

dbhelper = WorkflowDbHelper(
    input_user_or_path,
    input_database,
    input_backend,
    output_user_or_path,
    output_database,
    output_backend,
    shot_nr,
    run_in,
    run_out,
)
inputDb = dbhelper.getInputDatabase()
outputDb = dbhelper.getOutputDatabase()
machineDb = dbhelper.getMachineDatabase()

inputMds = ["nbi", "ic_antennas", "ec_launchers", "lh_antennas", "wall"]

# Prepare Memory DB
# Check if Machine description is exists and write to memory db
for idsName in inputMds:
    idsObject = get_ids(inputDb, idsName)

    if idsObject.ids_properties.homogeneous_time != imas.ids_defs.EMPTY_INT:
        machineDb.put(idsObject)
    else:
        print(f"{idsName} is not present in the scenario data, you can provide it with waveform cooker if required", file=sys.stderr)

waveform_presets = {
  "ec":{
     "custom":  ['ec_waveforms.yaml','Custom'],
     "preset1": ['ec_launchers_standard_Omode_mirrors.yaml','O-mode'],
     "preset2": ['ec_launchers_standard_Xmode_mirrors.yaml','X-mode']},
  "lh":{
     "custom":  ['lh_waveforms.yaml','Custom'],
     "preset1": ['None','Default']},
  "ic":{
     "custom":  ['ic_waveforms.yaml','nbi_waveforms.yaml','Custom'],
     "preset1": ['ic_53MHz_default.yaml','53 MHz']},
  "nbi":{
     "custom":  ['nbi_waveforms.yaml','Custom'],
     "preset1": ['nbi_D_1MeV_off_off.yaml','D 1MeV off-off'],
     "preset2": ['nbi_D_1MeV_off_on.yaml','D 1MeV off-on'],
     "preset3": ['nbi_D_1MeV_on_on.yaml','D 1MeV on-on'],
     "preset4": ['nbi_H_870keV_off_off.yaml','H 870keV off-off'],
     "preset5": ['nbi_H_870keV_off_on.yaml','H 870keV off-on'],
     "preset6": ['nbi_H_870keV_on_on.yaml','H 870keV on-on']}
    }
# Overwrite with configured waveform if it exists  to memory db
# waveform_presets = globallistReader.getWaveformPresetsList()
for filename in os.listdir(config_folder_path):
    filePath = os.path.join(config_folder_path, filename)
    if filePath.endswith("waveforms.yaml"):
        if os.path.exists(filePath):
            idsObject = add_dynamic(filePath) if isWaveformCookerPresent else None
        if idsObject is not None:
            machineDb.put(idsObject)

timeArray = dbhelper.getTimeArray(inputDb)

timenow = 320.00
equilibrium = get_ids(inputDb, "equilibrium", timenow)
core_profiles = get_ids(inputDb, "core_profiles", timenow)
workflow = get_ids(inputDb, "workflow", timenow)

nbi = get_ids(machineDb, "nbi", timenow)
ic_antennas = get_ids(machineDb, "ic_antennas", timenow)
ec_launchers = get_ids(machineDb, "ec_launchers", timenow)
lh_antennas = get_ids(machineDb, "lh_antennas", timenow)
wall = get_ids(machineDb, "wall", timenow)

hcdWorkflow = HCDWorkflow()
hcdWorkflow.initialize(config_folder_path)

# Set status TRUE for all processes
hcdWorkflow.setProcessStatus()

idsData = hcdWorkflow.run(
    equilibrium,
    core_profiles,
    workflow,
    nbi=nbi,
    ic_antennas=ic_antennas,
    ec_launchers=ec_launchers,
    lh_antennas=lh_antennas,
    wall=wall,
)

hcdWorkflow.finalize()

inputDb.close()
outputDb.close()
machineDb.close()

