# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
import datetime
sys.path.insert(0, os.path.abspath('../..'))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'HCD Workflow'
copyright = f"{datetime.datetime.now().year}, ITER Organization"
author = 'ITER Organization'
html_theme = "sphinx_immaterial"
html_title = project

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    "sphinx.ext.mathjax",
    "sphinx_immaterial",
]

templates_path = ['_templates']
exclude_patterns = []

# The suffix(es) of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_static_path = ['_static']

# Theme options 
html_theme_options = {
    "repo_url": "https://git.iter.org/projects/WF/repos/hcd-wf/browse",
    "repo_name": "HCD Workflow",
    "icon": {
        "repo": "fontawesome/brands/bitbucket",
    },
    # "toc_title_is_page_title": True,
    # "globaltoc_collapse": True,
    "features": [
        # "navigation.expand",
        # "navigation.tabs",
        "navigation.sections",
        "navigation.instant",
        # "header.autohide",
        "navigation.top",
        # "navigation.tracking",
        # "search.highlight",
        # "search.share",
        # "toc.integrate",
        # "toc.follow",
        "toc.sticky",
        # "content.tabs.link",
        "announce.dismiss",
    ],
    "palette": [
        {
            "media": "(prefers-color-scheme: light)",
            "scheme": "default",
            "primary": "blue",
            "accent": "light-green",
            "toggle": {
                "icon": "material/lightbulb-outline",
                "name": "Switch to dark mode",
            },
        },
        {
            "media": "(prefers-color-scheme: dark)",
            "scheme": "slate",
            "primary": "light-blue",
            "accent": "lime",
            "toggle": {
                "icon": "material/lightbulb",
                "name": "Switch to light mode",
            },
        },
    ],
    "globaltoc_collapse": False,
    "toc_title_is_page_title": False,
}
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# Additional HTML options
html_short_title = f"{project}"
html_show_sourcelink = True
html_show_sphinx = True
html_show_copyright = True

# -- Options for autodoc ----------------------------------------------------
autodoc_member_order = 'bysource'
autodoc_typehints = 'description'
# Runtime/GUI dependencies not installed in the docs build environment
autodoc_mock_imports = ['imas', 'matplotlib', 'tkinter', 'waveform_cooker']

# -- Options for intersphinx extension ---------------------------------------
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
}

# -- Options for todo extension ----------------------------------------------
todo_include_todos = True

